# https://golangci-lint.run/usage/configuration/
# Removed version field for v1 compatibility
linters-settings:
  lll:
    line-length: 180
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    # Includes rules G101-G602
    includes:
      - G101  # Look for hard coded credentials
      - G102  # Bind to all interfaces  
      - G103  # Audit the use of unsafe block
      - G104  # Audit errors not checked
      - G106  # Audit the use of ssh.InsecureIgnoreHostKey
      - G107  # Url provided to HTTP request as taint input
      - G108  # Profiling endpoint automatically exposed on /debug/pprof
      - G109  # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110  # Potential DoS vulnerability via decompression bomb
      - G201  # SQL query construction using format string
      - G202  # SQL query construction using string concatenation
      - G203  # Use of unescaped data in HTML templates
      - G204  # Audit use of command execution
      - G301  # Poor file permissions used when creating a directory
      - G302  # Poor file permissions used with chmod
      - G303  # Creating tempfile using a predictable path
      - G304  # File path provided as taint input
      - G305  # File traversal when extracting zip/tar archive
      - G306  # Poor file permissions used when writing to a new file
      - G307  # Deferring a method which returns an error
      - G401  # Detect the usage of DES, RC4, MD5 or SHA1
      - G402  # Look for bad TLS connection settings
      - G403  # Ensure minimum RSA key length of 2048 bits
      - G404  # Insecure random number source (rand)
      - G501  # Import blocklist: crypto/md5
      - G502  # Import blocklist: crypto/des
      - G503  # Import blocklist: crypto/rc4
      - G504  # Import blocklist: net/http/cgi
      - G505  # Import blocklist: crypto/sha1
      - G601  # Implicit memory aliasing of items from a range statement
      - G602  # Slice access out of bounds
    # Configuration of specific rules
    config:
      G101:
        pattern: (?i)(?:password|passwd|pwd|secret|token|key|api[_-]?key|private[_-]?key|credential)
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"
      G104:
        fmt: true
      G111:
        pattern: "(?i)dir.*traversal"
      G301: "0750"
      G302: "0600"
      G306: "0600"
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20
linters:
  # disable-all: true
  # Uncomment to enable all linters
  # enable-all: true
  # disabling linters that are abandoned or replaced with better versions
  disable:
#    - golint
#    - deadcode
#    - exhaustivestruct
#    - ifshort
#    - interfacer
#    - maligned
#    - nosnakecase
#    - scopelint
#    - structcheck
#    - varcheck
    - testpackage
    - forbidigo
    - paralleltest
    - varnamelen
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustruct
    - nolintlint
    - wrapcheck
# manual (these are now enabled above)
  # additional non-default linters that we want to use
  enable:
    - goconst
    - godox
    - misspell
    - ireturn
    - lll
    - nonamedreturns
    - staticcheck
    - ineffassign
    - govet
    - errcheck
    # Security and complexity linters
    - gosec
    - dupl
    - gocyclo
    - funlen
    - gocognit
    # Additional quality linters
    - gocritic
    - revive
    - unused
    - gochecknoglobals
    - err113
    # Style and performance linters
    - prealloc
    - unparam
    - unconvert
    - copyloopvar

issues:
  exclude-rules:
    # Exclude specific gosec rules in test files where they're expected
    - path: "_test\\.go"
      linters:
        - gosec
      text: "G104"  # Unchecked errors are acceptable in tests
    - path: "_test\\.go"
      linters:
        - gosec
      text: "G204"  # Command execution is expected in tests
    # Exclude G304 for specific config loading patterns
    - linters:
        - gosec
      text: "G304.*config"  # Config file loading from user input is expected
    # Exclude G304 for log file paths
    - linters:
        - gosec
      text: "G304.*log"  # Log file paths from user input are controlled
    # Exclude dupl in test files as test patterns are often duplicated
    - path: "_test\\.go"
      linters:
        - dupl
    # Exclude revive package-comments in test files
    - path: "_test\\.go" 
      linters:
        - revive
      text: "package-comments"
    # Exclude funlen in test files where long tests are acceptable
    - path: "_test\\.go"
      linters:
        - funlen
  max-same-issues: 0
  max-issues-per-linter: 0
