# https://golangci-lint.run/usage/configuration/
version: "2"
linters-settings:
  lll:
    line-length: 180
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    severity: medium
    confidence: medium
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20
linters:
  # disable-all: true
  # Uncomment to enable all linters
  # enable-all: true
  # disabling linters that are abandoned or replaced with better versions
  disable:
#    - golint
#    - deadcode
#    - exhaustivestruct
#    - ifshort
#    - interfacer
#    - maligned
#    - nosnakecase
#    - scopelint
#    - structcheck
#    - varcheck
    - testpackage
    - forbidigo
    - paralleltest
    - varnamelen
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustruct
    - nolintlint
    - wrapcheck
# manual (these are now enabled above)
  # additional non-default linters that we want to use
  enable:
    - goconst
    - godox
    - misspell
    - ireturn
    - lll
    - nonamedreturns
    - staticcheck
    - ineffassign
    - govet
    - errcheck
    # Security and complexity linters
    - gosec
    - dupl
    - gocyclo
    - funlen
    - gocognit
    # Additional quality linters
    - gocritic
    - revive
    - unused
    - gochecknoglobals
    - err113
    # Style and performance linters
    - prealloc
    - unparam
    - unconvert
    - copyloopvar

issues:
  exclude-rules:
    # Exclude some gosec rules that are too noisy for this codebase
    - linters:
        - gosec
      text: "G104"  # Ignore audit errors for now
    - linters:
        - gosec  
      text: "G304"  # File path from user input - some are expected
    # Exclude dupl in test files as test patterns are often duplicated
    - path: "_test\\.go"
      linters:
        - dupl
    # Exclude revive package-comments in test files
    - path: "_test\\.go" 
      linters:
        - revive
      text: "package-comments"
    # Exclude funlen in test files where long tests are acceptable
    - path: "_test\\.go"
      linters:
        - funlen
  max-same-issues: 0
  max-issues-per-linter: 0
