linters-settings:
  lll:
    line-length: 180
linters:
  # disable-all: true
  # Uncomment to enable all linters
  # enable-all: true
  # disabling linters that are abandoned or replaced with better versions
  disable:
#    - golint
#    - deadcode
#    - exhaustivestruct
#    - ifshort
#    - interfacer
#    - maligned
#    - nosnakecase
#    - scopelint
#    - structcheck
#    - varcheck
    - testpackage
    - forbidigo
    - paralleltest
    - varnamelen
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustruct
    - nolintlint
    - wrapcheck
  # additional non-default linters that we want to use
  enable:
    - gochecknoglobals
    - gocritic
    - goconst
    - godox
    - err113
    - gofmt
    - gosec
    - misspell
    - revive
    - funlen
    - ireturn
    - lll
    - nonamedreturns
