// Code generated by MockGen. DO NOT EDIT.
// Source: internal/git/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/git/interfaces.go -destination=internal/git/mocks/git_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	git "github.com/gizzahub/gzh-cli/internal/git"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddRemote mocks base method.
func (m *MockClient) AddRemote(ctx context.Context, repoPath, name, url string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemote", ctx, repoPath, name, url)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRemote indicates an expected call of AddRemote.
func (mr *MockClientMockRecorder) AddRemote(ctx, repoPath, name, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemote", reflect.TypeOf((*MockClient)(nil).AddRemote), ctx, repoPath, name, url)
}

// CheckoutBranch mocks base method.
func (m *MockClient) CheckoutBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockClientMockRecorder) CheckoutBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockClient)(nil).CheckoutBranch), ctx, repoPath, branchName)
}

// Clone mocks base method.
func (m *MockClient) Clone(ctx context.Context, options git.CloneOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockClientMockRecorder) Clone(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockClient)(nil).Clone), ctx, options)
}

// CreateBranch mocks base method.
func (m *MockClient) CreateBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch indicates an expected call of CreateBranch.
func (mr *MockClientMockRecorder) CreateBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockClient)(nil).CreateBranch), ctx, repoPath, branchName)
}

// DeleteBranch mocks base method.
func (m *MockClient) DeleteBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockClientMockRecorder) DeleteBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockClient)(nil).DeleteBranch), ctx, repoPath, branchName)
}

// Fetch mocks base method.
func (m *MockClient) Fetch(ctx context.Context, repoPath, remote string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, repoPath, remote)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockClientMockRecorder) Fetch(ctx, repoPath, remote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockClient)(nil).Fetch), ctx, repoPath, remote)
}

// GetCommitHistory mocks base method.
func (m *MockClient) GetCommitHistory(ctx context.Context, repoPath string, limit int) ([]git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitHistory", ctx, repoPath, limit)
	ret0, _ := ret[0].([]git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitHistory indicates an expected call of GetCommitHistory.
func (mr *MockClientMockRecorder) GetCommitHistory(ctx, repoPath, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitHistory", reflect.TypeOf((*MockClient)(nil).GetCommitHistory), ctx, repoPath, limit)
}

// GetCurrentBranch mocks base method.
func (m *MockClient) GetCurrentBranch(ctx context.Context, repoPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranch", ctx, repoPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranch indicates an expected call of GetCurrentBranch.
func (mr *MockClientMockRecorder) GetCurrentBranch(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranch", reflect.TypeOf((*MockClient)(nil).GetCurrentBranch), ctx, repoPath)
}

// GetDefaultBranch mocks base method.
func (m *MockClient) GetDefaultBranch(ctx context.Context, repoPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultBranch", ctx, repoPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultBranch indicates an expected call of GetDefaultBranch.
func (mr *MockClientMockRecorder) GetDefaultBranch(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultBranch", reflect.TypeOf((*MockClient)(nil).GetDefaultBranch), ctx, repoPath)
}

// GetLastCommit mocks base method.
func (m *MockClient) GetLastCommit(ctx context.Context, repoPath string) (*git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", ctx, repoPath)
	ret0, _ := ret[0].(*git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockClientMockRecorder) GetLastCommit(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockClient)(nil).GetLastCommit), ctx, repoPath)
}

// GetRepository mocks base method.
func (m *MockClient) GetRepository(ctx context.Context, path string) (*git.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, path)
	ret0, _ := ret[0].(*git.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockClientMockRecorder) GetRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockClient)(nil).GetRepository), ctx, path)
}

// GetStatus mocks base method.
func (m *MockClient) GetStatus(ctx context.Context, repoPath string) (*git.StatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, repoPath)
	ret0, _ := ret[0].(*git.StatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockClientMockRecorder) GetStatus(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockClient)(nil).GetStatus), ctx, repoPath)
}

// IsDirty mocks base method.
func (m *MockClient) IsDirty(ctx context.Context, repoPath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty", ctx, repoPath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockClientMockRecorder) IsDirty(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockClient)(nil).IsDirty), ctx, repoPath)
}

// IsRepository mocks base method.
func (m *MockClient) IsRepository(ctx context.Context, path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRepository", ctx, path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRepository indicates an expected call of IsRepository.
func (mr *MockClientMockRecorder) IsRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRepository", reflect.TypeOf((*MockClient)(nil).IsRepository), ctx, path)
}

// ListBranches mocks base method.
func (m *MockClient) ListBranches(ctx context.Context, repoPath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", ctx, repoPath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockClientMockRecorder) ListBranches(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockClient)(nil).ListBranches), ctx, repoPath)
}

// ListRemotes mocks base method.
func (m *MockClient) ListRemotes(ctx context.Context, repoPath string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemotes", ctx, repoPath)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemotes indicates an expected call of ListRemotes.
func (mr *MockClientMockRecorder) ListRemotes(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemotes", reflect.TypeOf((*MockClient)(nil).ListRemotes), ctx, repoPath)
}

// Pull mocks base method.
func (m *MockClient) Pull(ctx context.Context, repoPath string, options git.PullOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, repoPath, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockClientMockRecorder) Pull(ctx, repoPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockClient)(nil).Pull), ctx, repoPath, options)
}

// RemoveRemote mocks base method.
func (m *MockClient) RemoveRemote(ctx context.Context, repoPath, name string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRemote", ctx, repoPath, name)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveRemote indicates an expected call of RemoveRemote.
func (mr *MockClientMockRecorder) RemoveRemote(ctx, repoPath, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRemote", reflect.TypeOf((*MockClient)(nil).RemoveRemote), ctx, repoPath, name)
}

// Reset mocks base method.
func (m *MockClient) Reset(ctx context.Context, repoPath string, options git.ResetOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, repoPath, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reset indicates an expected call of Reset.
func (mr *MockClientMockRecorder) Reset(ctx, repoPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockClient)(nil).Reset), ctx, repoPath, options)
}

// SetRemoteURL mocks base method.
func (m *MockClient) SetRemoteURL(ctx context.Context, repoPath, remote, url string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteURL", ctx, repoPath, remote, url)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRemoteURL indicates an expected call of SetRemoteURL.
func (mr *MockClientMockRecorder) SetRemoteURL(ctx, repoPath, remote, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteURL", reflect.TypeOf((*MockClient)(nil).SetRemoteURL), ctx, repoPath, remote, url)
}

// ValidateRepository mocks base method.
func (m *MockClient) ValidateRepository(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepository", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepository indicates an expected call of ValidateRepository.
func (mr *MockClientMockRecorder) ValidateRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepository", reflect.TypeOf((*MockClient)(nil).ValidateRepository), ctx, path)
}

// MockStrategyExecutor is a mock of StrategyExecutor interface.
type MockStrategyExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyExecutorMockRecorder
	isgomock struct{}
}

// MockStrategyExecutorMockRecorder is the mock recorder for MockStrategyExecutor.
type MockStrategyExecutorMockRecorder struct {
	mock *MockStrategyExecutor
}

// NewMockStrategyExecutor creates a new mock instance.
func NewMockStrategyExecutor(ctrl *gomock.Controller) *MockStrategyExecutor {
	mock := &MockStrategyExecutor{ctrl: ctrl}
	mock.recorder = &MockStrategyExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategyExecutor) EXPECT() *MockStrategyExecutorMockRecorder {
	return m.recorder
}

// ExecuteStrategy mocks base method.
func (m *MockStrategyExecutor) ExecuteStrategy(ctx context.Context, repoPath, strategy string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStrategy", ctx, repoPath, strategy)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStrategy indicates an expected call of ExecuteStrategy.
func (mr *MockStrategyExecutorMockRecorder) ExecuteStrategy(ctx, repoPath, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStrategy", reflect.TypeOf((*MockStrategyExecutor)(nil).ExecuteStrategy), ctx, repoPath, strategy)
}

// GetStrategyDescription mocks base method.
func (m *MockStrategyExecutor) GetStrategyDescription(strategy string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrategyDescription", strategy)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStrategyDescription indicates an expected call of GetStrategyDescription.
func (mr *MockStrategyExecutorMockRecorder) GetStrategyDescription(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrategyDescription", reflect.TypeOf((*MockStrategyExecutor)(nil).GetStrategyDescription), strategy)
}

// GetSupportedStrategies mocks base method.
func (m *MockStrategyExecutor) GetSupportedStrategies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedStrategies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedStrategies indicates an expected call of GetSupportedStrategies.
func (mr *MockStrategyExecutorMockRecorder) GetSupportedStrategies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedStrategies", reflect.TypeOf((*MockStrategyExecutor)(nil).GetSupportedStrategies))
}

// IsValidStrategy mocks base method.
func (m *MockStrategyExecutor) IsValidStrategy(strategy string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidStrategy", strategy)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidStrategy indicates an expected call of IsValidStrategy.
func (mr *MockStrategyExecutorMockRecorder) IsValidStrategy(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidStrategy", reflect.TypeOf((*MockStrategyExecutor)(nil).IsValidStrategy), strategy)
}

// MockBulkOperator is a mock of BulkOperator interface.
type MockBulkOperator struct {
	ctrl     *gomock.Controller
	recorder *MockBulkOperatorMockRecorder
	isgomock struct{}
}

// MockBulkOperatorMockRecorder is the mock recorder for MockBulkOperator.
type MockBulkOperatorMockRecorder struct {
	mock *MockBulkOperator
}

// NewMockBulkOperator creates a new mock instance.
func NewMockBulkOperator(ctrl *gomock.Controller) *MockBulkOperator {
	mock := &MockBulkOperator{ctrl: ctrl}
	mock.recorder = &MockBulkOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkOperator) EXPECT() *MockBulkOperatorMockRecorder {
	return m.recorder
}

// ExecuteBulkOperation mocks base method.
func (m *MockBulkOperator) ExecuteBulkOperation(ctx context.Context, repoPaths []string, operation git.BulkOperation) ([]git.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkOperation", ctx, repoPaths, operation)
	ret0, _ := ret[0].([]git.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkOperation indicates an expected call of ExecuteBulkOperation.
func (mr *MockBulkOperatorMockRecorder) ExecuteBulkOperation(ctx, repoPaths, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkOperation", reflect.TypeOf((*MockBulkOperator)(nil).ExecuteBulkOperation), ctx, repoPaths, operation)
}

// ExecuteBulkOperationWithOptions mocks base method.
func (m *MockBulkOperator) ExecuteBulkOperationWithOptions(ctx context.Context, repoPaths []string, operation git.BulkOperation, options git.BulkOptions) ([]git.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkOperationWithOptions", ctx, repoPaths, operation, options)
	ret0, _ := ret[0].([]git.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkOperationWithOptions indicates an expected call of ExecuteBulkOperationWithOptions.
func (mr *MockBulkOperatorMockRecorder) ExecuteBulkOperationWithOptions(ctx, repoPaths, operation, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkOperationWithOptions", reflect.TypeOf((*MockBulkOperator)(nil).ExecuteBulkOperationWithOptions), ctx, repoPaths, operation, options)
}

// GetProgress mocks base method.
func (m *MockBulkOperator) GetProgress() <-chan git.BulkProgress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress")
	ret0, _ := ret[0].(<-chan git.BulkProgress)
	return ret0
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockBulkOperatorMockRecorder) GetProgress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockBulkOperator)(nil).GetProgress))
}

// MockAuthManager is a mock of AuthManager interface.
type MockAuthManager struct {
	ctrl     *gomock.Controller
	recorder *MockAuthManagerMockRecorder
	isgomock struct{}
}

// MockAuthManagerMockRecorder is the mock recorder for MockAuthManager.
type MockAuthManagerMockRecorder struct {
	mock *MockAuthManager
}

// NewMockAuthManager creates a new mock instance.
func NewMockAuthManager(ctrl *gomock.Controller) *MockAuthManager {
	mock := &MockAuthManager{ctrl: ctrl}
	mock.recorder = &MockAuthManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthManager) EXPECT() *MockAuthManagerMockRecorder {
	return m.recorder
}

// ConfigurePasswordAuth mocks base method.
func (m *MockAuthManager) ConfigurePasswordAuth(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigurePasswordAuth", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigurePasswordAuth indicates an expected call of ConfigurePasswordAuth.
func (mr *MockAuthManagerMockRecorder) ConfigurePasswordAuth(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigurePasswordAuth", reflect.TypeOf((*MockAuthManager)(nil).ConfigurePasswordAuth), ctx, username, password)
}

// ConfigureSSHAuth mocks base method.
func (m *MockAuthManager) ConfigureSSHAuth(ctx context.Context, keyPath, passphrase string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureSSHAuth", ctx, keyPath, passphrase)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureSSHAuth indicates an expected call of ConfigureSSHAuth.
func (mr *MockAuthManagerMockRecorder) ConfigureSSHAuth(ctx, keyPath, passphrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureSSHAuth", reflect.TypeOf((*MockAuthManager)(nil).ConfigureSSHAuth), ctx, keyPath, passphrase)
}

// ConfigureTokenAuth mocks base method.
func (m *MockAuthManager) ConfigureTokenAuth(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureTokenAuth", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureTokenAuth indicates an expected call of ConfigureTokenAuth.
func (mr *MockAuthManagerMockRecorder) ConfigureTokenAuth(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureTokenAuth", reflect.TypeOf((*MockAuthManager)(nil).ConfigureTokenAuth), ctx, token)
}

// GetAuthMethod mocks base method.
func (m *MockAuthManager) GetAuthMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthMethod indicates an expected call of GetAuthMethod.
func (mr *MockAuthManagerMockRecorder) GetAuthMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthMethod", reflect.TypeOf((*MockAuthManager)(nil).GetAuthMethod))
}

// ValidateAuth mocks base method.
func (m *MockAuthManager) ValidateAuth(ctx context.Context, remoteURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAuth", ctx, remoteURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAuth indicates an expected call of ValidateAuth.
func (mr *MockAuthManagerMockRecorder) ValidateAuth(ctx, remoteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAuth", reflect.TypeOf((*MockAuthManager)(nil).ValidateAuth), ctx, remoteURL)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddRemote mocks base method.
func (m *MockService) AddRemote(ctx context.Context, repoPath, name, url string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemote", ctx, repoPath, name, url)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRemote indicates an expected call of AddRemote.
func (mr *MockServiceMockRecorder) AddRemote(ctx, repoPath, name, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemote", reflect.TypeOf((*MockService)(nil).AddRemote), ctx, repoPath, name, url)
}

// CheckoutBranch mocks base method.
func (m *MockService) CheckoutBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockServiceMockRecorder) CheckoutBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockService)(nil).CheckoutBranch), ctx, repoPath, branchName)
}

// Clone mocks base method.
func (m *MockService) Clone(ctx context.Context, options git.CloneOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockServiceMockRecorder) Clone(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockService)(nil).Clone), ctx, options)
}

// ConfigurePasswordAuth mocks base method.
func (m *MockService) ConfigurePasswordAuth(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigurePasswordAuth", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigurePasswordAuth indicates an expected call of ConfigurePasswordAuth.
func (mr *MockServiceMockRecorder) ConfigurePasswordAuth(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigurePasswordAuth", reflect.TypeOf((*MockService)(nil).ConfigurePasswordAuth), ctx, username, password)
}

// ConfigureSSHAuth mocks base method.
func (m *MockService) ConfigureSSHAuth(ctx context.Context, keyPath, passphrase string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureSSHAuth", ctx, keyPath, passphrase)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureSSHAuth indicates an expected call of ConfigureSSHAuth.
func (mr *MockServiceMockRecorder) ConfigureSSHAuth(ctx, keyPath, passphrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureSSHAuth", reflect.TypeOf((*MockService)(nil).ConfigureSSHAuth), ctx, keyPath, passphrase)
}

// ConfigureTokenAuth mocks base method.
func (m *MockService) ConfigureTokenAuth(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureTokenAuth", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureTokenAuth indicates an expected call of ConfigureTokenAuth.
func (mr *MockServiceMockRecorder) ConfigureTokenAuth(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureTokenAuth", reflect.TypeOf((*MockService)(nil).ConfigureTokenAuth), ctx, token)
}

// CreateBranch mocks base method.
func (m *MockService) CreateBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch indicates an expected call of CreateBranch.
func (mr *MockServiceMockRecorder) CreateBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockService)(nil).CreateBranch), ctx, repoPath, branchName)
}

// DeleteBranch mocks base method.
func (m *MockService) DeleteBranch(ctx context.Context, repoPath, branchName string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranch", ctx, repoPath, branchName)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockServiceMockRecorder) DeleteBranch(ctx, repoPath, branchName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockService)(nil).DeleteBranch), ctx, repoPath, branchName)
}

// ExecuteBulkOperation mocks base method.
func (m *MockService) ExecuteBulkOperation(ctx context.Context, repoPaths []string, operation git.BulkOperation) ([]git.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkOperation", ctx, repoPaths, operation)
	ret0, _ := ret[0].([]git.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkOperation indicates an expected call of ExecuteBulkOperation.
func (mr *MockServiceMockRecorder) ExecuteBulkOperation(ctx, repoPaths, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkOperation", reflect.TypeOf((*MockService)(nil).ExecuteBulkOperation), ctx, repoPaths, operation)
}

// ExecuteBulkOperationWithOptions mocks base method.
func (m *MockService) ExecuteBulkOperationWithOptions(ctx context.Context, repoPaths []string, operation git.BulkOperation, options git.BulkOptions) ([]git.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkOperationWithOptions", ctx, repoPaths, operation, options)
	ret0, _ := ret[0].([]git.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkOperationWithOptions indicates an expected call of ExecuteBulkOperationWithOptions.
func (mr *MockServiceMockRecorder) ExecuteBulkOperationWithOptions(ctx, repoPaths, operation, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkOperationWithOptions", reflect.TypeOf((*MockService)(nil).ExecuteBulkOperationWithOptions), ctx, repoPaths, operation, options)
}

// ExecuteStrategy mocks base method.
func (m *MockService) ExecuteStrategy(ctx context.Context, repoPath, strategy string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStrategy", ctx, repoPath, strategy)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStrategy indicates an expected call of ExecuteStrategy.
func (mr *MockServiceMockRecorder) ExecuteStrategy(ctx, repoPath, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStrategy", reflect.TypeOf((*MockService)(nil).ExecuteStrategy), ctx, repoPath, strategy)
}

// Fetch mocks base method.
func (m *MockService) Fetch(ctx context.Context, repoPath, remote string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, repoPath, remote)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockServiceMockRecorder) Fetch(ctx, repoPath, remote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockService)(nil).Fetch), ctx, repoPath, remote)
}

// GetAuthMethod mocks base method.
func (m *MockService) GetAuthMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthMethod indicates an expected call of GetAuthMethod.
func (mr *MockServiceMockRecorder) GetAuthMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthMethod", reflect.TypeOf((*MockService)(nil).GetAuthMethod))
}

// GetCommitHistory mocks base method.
func (m *MockService) GetCommitHistory(ctx context.Context, repoPath string, limit int) ([]git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitHistory", ctx, repoPath, limit)
	ret0, _ := ret[0].([]git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitHistory indicates an expected call of GetCommitHistory.
func (mr *MockServiceMockRecorder) GetCommitHistory(ctx, repoPath, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitHistory", reflect.TypeOf((*MockService)(nil).GetCommitHistory), ctx, repoPath, limit)
}

// GetCurrentBranch mocks base method.
func (m *MockService) GetCurrentBranch(ctx context.Context, repoPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranch", ctx, repoPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranch indicates an expected call of GetCurrentBranch.
func (mr *MockServiceMockRecorder) GetCurrentBranch(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranch", reflect.TypeOf((*MockService)(nil).GetCurrentBranch), ctx, repoPath)
}

// GetDefaultBranch mocks base method.
func (m *MockService) GetDefaultBranch(ctx context.Context, repoPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultBranch", ctx, repoPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultBranch indicates an expected call of GetDefaultBranch.
func (mr *MockServiceMockRecorder) GetDefaultBranch(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultBranch", reflect.TypeOf((*MockService)(nil).GetDefaultBranch), ctx, repoPath)
}

// GetLastCommit mocks base method.
func (m *MockService) GetLastCommit(ctx context.Context, repoPath string) (*git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", ctx, repoPath)
	ret0, _ := ret[0].(*git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockServiceMockRecorder) GetLastCommit(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockService)(nil).GetLastCommit), ctx, repoPath)
}

// GetProgress mocks base method.
func (m *MockService) GetProgress() <-chan git.BulkProgress {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress")
	ret0, _ := ret[0].(<-chan git.BulkProgress)
	return ret0
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockServiceMockRecorder) GetProgress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockService)(nil).GetProgress))
}

// GetRepository mocks base method.
func (m *MockService) GetRepository(ctx context.Context, path string) (*git.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, path)
	ret0, _ := ret[0].(*git.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockServiceMockRecorder) GetRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockService)(nil).GetRepository), ctx, path)
}

// GetStatus mocks base method.
func (m *MockService) GetStatus(ctx context.Context, repoPath string) (*git.StatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, repoPath)
	ret0, _ := ret[0].(*git.StatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockServiceMockRecorder) GetStatus(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockService)(nil).GetStatus), ctx, repoPath)
}

// GetStrategyDescription mocks base method.
func (m *MockService) GetStrategyDescription(strategy string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrategyDescription", strategy)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStrategyDescription indicates an expected call of GetStrategyDescription.
func (mr *MockServiceMockRecorder) GetStrategyDescription(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrategyDescription", reflect.TypeOf((*MockService)(nil).GetStrategyDescription), strategy)
}

// GetSupportedStrategies mocks base method.
func (m *MockService) GetSupportedStrategies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedStrategies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedStrategies indicates an expected call of GetSupportedStrategies.
func (mr *MockServiceMockRecorder) GetSupportedStrategies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedStrategies", reflect.TypeOf((*MockService)(nil).GetSupportedStrategies))
}

// IsDirty mocks base method.
func (m *MockService) IsDirty(ctx context.Context, repoPath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty", ctx, repoPath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockServiceMockRecorder) IsDirty(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockService)(nil).IsDirty), ctx, repoPath)
}

// IsRepository mocks base method.
func (m *MockService) IsRepository(ctx context.Context, path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRepository", ctx, path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRepository indicates an expected call of IsRepository.
func (mr *MockServiceMockRecorder) IsRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRepository", reflect.TypeOf((*MockService)(nil).IsRepository), ctx, path)
}

// IsValidStrategy mocks base method.
func (m *MockService) IsValidStrategy(strategy string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidStrategy", strategy)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidStrategy indicates an expected call of IsValidStrategy.
func (mr *MockServiceMockRecorder) IsValidStrategy(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidStrategy", reflect.TypeOf((*MockService)(nil).IsValidStrategy), strategy)
}

// ListBranches mocks base method.
func (m *MockService) ListBranches(ctx context.Context, repoPath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", ctx, repoPath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockServiceMockRecorder) ListBranches(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockService)(nil).ListBranches), ctx, repoPath)
}

// ListRemotes mocks base method.
func (m *MockService) ListRemotes(ctx context.Context, repoPath string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemotes", ctx, repoPath)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemotes indicates an expected call of ListRemotes.
func (mr *MockServiceMockRecorder) ListRemotes(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemotes", reflect.TypeOf((*MockService)(nil).ListRemotes), ctx, repoPath)
}

// Pull mocks base method.
func (m *MockService) Pull(ctx context.Context, repoPath string, options git.PullOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, repoPath, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockServiceMockRecorder) Pull(ctx, repoPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockService)(nil).Pull), ctx, repoPath, options)
}

// RemoveRemote mocks base method.
func (m *MockService) RemoveRemote(ctx context.Context, repoPath, name string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRemote", ctx, repoPath, name)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveRemote indicates an expected call of RemoveRemote.
func (mr *MockServiceMockRecorder) RemoveRemote(ctx, repoPath, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRemote", reflect.TypeOf((*MockService)(nil).RemoveRemote), ctx, repoPath, name)
}

// Reset mocks base method.
func (m *MockService) Reset(ctx context.Context, repoPath string, options git.ResetOptions) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, repoPath, options)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reset indicates an expected call of Reset.
func (mr *MockServiceMockRecorder) Reset(ctx, repoPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockService)(nil).Reset), ctx, repoPath, options)
}

// SetRemoteURL mocks base method.
func (m *MockService) SetRemoteURL(ctx context.Context, repoPath, remote, url string) (*git.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteURL", ctx, repoPath, remote, url)
	ret0, _ := ret[0].(*git.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRemoteURL indicates an expected call of SetRemoteURL.
func (mr *MockServiceMockRecorder) SetRemoteURL(ctx, repoPath, remote, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteURL", reflect.TypeOf((*MockService)(nil).SetRemoteURL), ctx, repoPath, remote, url)
}

// ValidateAuth mocks base method.
func (m *MockService) ValidateAuth(ctx context.Context, remoteURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAuth", ctx, remoteURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAuth indicates an expected call of ValidateAuth.
func (mr *MockServiceMockRecorder) ValidateAuth(ctx, remoteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAuth", reflect.TypeOf((*MockService)(nil).ValidateAuth), ctx, remoteURL)
}

// ValidateRepository mocks base method.
func (m *MockService) ValidateRepository(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepository", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepository indicates an expected call of ValidateRepository.
func (mr *MockServiceMockRecorder) ValidateRepository(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepository", reflect.TypeOf((*MockService)(nil).ValidateRepository), ctx, path)
}
