# Repository Configuration Schema
# This file defines the structure for managing GitHub repository configurations

# Schema version (required)
version: "1.0.0"

# GitHub organization (required)
organization: "my-organization"

# Default settings applied to all repositories unless overridden
defaults:
  template: "standard" # Reference to a template
  settings:
    private: true
    has_issues: true
    has_wiki: false
    has_projects: false
    delete_branch_on_merge: true

# Reusable configuration templates
templates:
  # Standard template for most repositories
  standard:
    description: "Standard repository configuration"
    settings:
      has_issues: true
      has_wiki: false
      has_projects: false
      has_downloads: false
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false
      delete_branch_on_merge: true
    security:
      vulnerability_alerts: true
      security_advisories: true
      branch_protection:
        main:
          required_reviews: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: false
          required_status_checks:
            - "ci/build"
            - "ci/test"
          strict_status_checks: true
          enforce_admins: false

  # High security template for sensitive repositories
  security:
    base: "standard" # Inherit from standard template
    description: "High security repository configuration"
    settings:
      private: true
    security:
      private_vulnerability_reporting: true
      branch_protection:
        main:
          required_reviews: 2
          require_code_owner_reviews: true
          restrict_pushes: true
          allowed_teams:
            - "security-team"
            - "admin-team"
          enforce_admins: true
          allow_force_pushes: false
          allow_deletions: false
    permissions:
      team_permissions:
        "security-team": "admin"
        "dev-team": "push"

  # Open source template for public repositories
  opensource:
    description: "Open source repository configuration"
    settings:
      private: false
      has_issues: true
      has_wiki: true
      has_projects: true
      topics:
        - "open-source"
        - "community"
    security:
      branch_protection:
        main:
          required_reviews: 1
          dismiss_stale_reviews: false
          required_status_checks:
            - "ci/build"
            - "ci/test"
            - "ci/license-check"

  # Microservice template
  microservice:
    base: "standard"
    description: "Microservice repository configuration"
    settings:
      topics:
        - "microservice"
        - "api"
    security:
      webhooks:
        - url: "${DEPLOYMENT_WEBHOOK_URL}"
          events:
            - "push"
            - "release"
          content_type: "json"
          secret: "${WEBHOOK_SECRET}"

# Repository-specific configurations
repositories:
  # Specific repository configurations
  specific:
    - name: "api-gateway"
      template: "microservice"
      settings:
        description: "Main API gateway service"
        homepage: "https://api.example.com"
        topics:
          - "api-gateway"
          - "microservice"
          - "critical"
      security:
        branch_protection:
          main:
            required_reviews: 3 # Override template setting

    - name: "documentation"
      template: "opensource"
      settings:
        description: "Public documentation repository"
        homepage: "https://docs.example.com"
        has_wiki: true
        has_projects: true

    - name: "infrastructure"
      template: "security"
      settings:
        description: "Infrastructure as Code repository"
        topics:
          - "terraform"
          - "infrastructure"
          - "iac"

  # Pattern-based configurations
  patterns:
    - match: "service-*"
      template: "microservice"
      settings:
        topics:
          - "microservice"

    - match: "lib-*"
      template: "standard"
      settings:
        topics:
          - "library"
        has_downloads: true

    - match: "*-frontend"
      settings:
        topics:
          - "frontend"
          - "react"
        has_projects: true

  # Default configuration for repositories not matching above
  default:
    template: "standard"

# Policy templates for compliance
policies:
  security_compliance:
    description: "Security compliance policy"
    rules:
      branch_protection_required:
        type: "branch_protection"
        value: true
        enforcement: "required"

      min_reviewers:
        type: "min_reviews"
        value: 1
        enforcement: "required"

      vulnerability_scanning:
        type: "security_feature"
        value: "vulnerability_alerts"
        enforcement: "required"

  opensource_compliance:
    description: "Open source compliance policy"
    rules:
      license_required:
        type: "file_exists"
        value: "LICENSE"
        enforcement: "required"

      readme_required:
        type: "file_exists"
        value: "README.md"
        enforcement: "required"

      contributing_guide:
        type: "file_exists"
        value: "CONTRIBUTING.md"
        enforcement: "recommended"
