// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/synclone/facade.go
//
// Generated by this command:
//
//	mockgen -source=pkg/synclone/facade.go -destination=pkg/synclone/mocks/bulk_clone_manager_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bulkclone "github.com/gizzahub/gzh-cli/pkg/synclone"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CleanupRepositories mocks base method.
func (m *MockManager) CleanupRepositories(ctx context.Context, request *bulkclone.CleanupRequest) (*bulkclone.CleanupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupRepositories", ctx, request)
	ret0, _ := ret[0].(*bulkclone.CleanupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupRepositories indicates an expected call of CleanupRepositories.
func (mr *MockManagerMockRecorder) CleanupRepositories(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupRepositories", reflect.TypeOf((*MockManager)(nil).CleanupRepositories), ctx, request)
}

// CloneOrganization mocks base method.
func (m *MockManager) CloneOrganization(ctx context.Context, request *bulkclone.OrganizationCloneRequest) (*bulkclone.CloneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneOrganization", ctx, request)
	ret0, _ := ret[0].(*bulkclone.CloneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneOrganization indicates an expected call of CloneOrganization.
func (mr *MockManagerMockRecorder) CloneOrganization(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneOrganization", reflect.TypeOf((*MockManager)(nil).CloneOrganization), ctx, request)
}

// CloneRepositories mocks base method.
func (m *MockManager) CloneRepositories(ctx context.Context, request *bulkclone.RepositoryCloneRequest) (*bulkclone.CloneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneRepositories", ctx, request)
	ret0, _ := ret[0].(*bulkclone.CloneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneRepositories indicates an expected call of CloneRepositories.
func (mr *MockManagerMockRecorder) CloneRepositories(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneRepositories", reflect.TypeOf((*MockManager)(nil).CloneRepositories), ctx, request)
}

// DiscoverRepositories mocks base method.
func (m *MockManager) DiscoverRepositories(ctx context.Context, request *bulkclone.DiscoveryRequest) (*bulkclone.DiscoveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverRepositories", ctx, request)
	ret0, _ := ret[0].(*bulkclone.DiscoveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverRepositories indicates an expected call of DiscoverRepositories.
func (mr *MockManagerMockRecorder) DiscoverRepositories(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverRepositories", reflect.TypeOf((*MockManager)(nil).DiscoverRepositories), ctx, request)
}

// GetRepositoryStatus mocks base method.
func (m *MockManager) GetRepositoryStatus(ctx context.Context, targetPath string) (*bulkclone.RepositoryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryStatus", ctx, targetPath)
	ret0, _ := ret[0].(*bulkclone.RepositoryStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryStatus indicates an expected call of GetRepositoryStatus.
func (mr *MockManagerMockRecorder) GetRepositoryStatus(ctx, targetPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryStatus", reflect.TypeOf((*MockManager)(nil).GetRepositoryStatus), ctx, targetPath)
}

// ListAvailableOrganizations mocks base method.
func (m *MockManager) ListAvailableOrganizations(ctx context.Context, provider string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableOrganizations", ctx, provider)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableOrganizations indicates an expected call of ListAvailableOrganizations.
func (mr *MockManagerMockRecorder) ListAvailableOrganizations(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableOrganizations", reflect.TypeOf((*MockManager)(nil).ListAvailableOrganizations), ctx, provider)
}

// LoadConfiguration mocks base method.
func (m *MockManager) LoadConfiguration(ctx context.Context) (*bulkclone.BulkCloneConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfiguration", ctx)
	ret0, _ := ret[0].(*bulkclone.BulkCloneConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfiguration indicates an expected call of LoadConfiguration.
func (mr *MockManagerMockRecorder) LoadConfiguration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfiguration", reflect.TypeOf((*MockManager)(nil).LoadConfiguration), ctx)
}

// LoadConfigurationFromFile mocks base method.
func (m *MockManager) LoadConfigurationFromFile(ctx context.Context, filename string) (*bulkclone.BulkCloneConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigurationFromFile", ctx, filename)
	ret0, _ := ret[0].(*bulkclone.BulkCloneConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfigurationFromFile indicates an expected call of LoadConfigurationFromFile.
func (mr *MockManagerMockRecorder) LoadConfigurationFromFile(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigurationFromFile", reflect.TypeOf((*MockManager)(nil).LoadConfigurationFromFile), ctx, filename)
}

// RefreshRepositories mocks base method.
func (m *MockManager) RefreshRepositories(ctx context.Context, request *bulkclone.RefreshRequest) (*bulkclone.RefreshResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshRepositories", ctx, request)
	ret0, _ := ret[0].(*bulkclone.RefreshResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshRepositories indicates an expected call of RefreshRepositories.
func (mr *MockManagerMockRecorder) RefreshRepositories(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshRepositories", reflect.TypeOf((*MockManager)(nil).RefreshRepositories), ctx, request)
}

// ValidateConfiguration mocks base method.
func (m *MockManager) ValidateConfiguration(ctx context.Context, config *bulkclone.BulkCloneConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfiguration", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfiguration indicates an expected call of ValidateConfiguration.
func (mr *MockManagerMockRecorder) ValidateConfiguration(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfiguration", reflect.TypeOf((*MockManager)(nil).ValidateConfiguration), ctx, config)
}

// MockConfigurationManager is a mock of ConfigurationManager interface.
type MockConfigurationManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationManagerMockRecorder
	isgomock struct{}
}

// MockConfigurationManagerMockRecorder is the mock recorder for MockConfigurationManager.
type MockConfigurationManagerMockRecorder struct {
	mock *MockConfigurationManager
}

// NewMockConfigurationManager creates a new mock instance.
func NewMockConfigurationManager(ctrl *gomock.Controller) *MockConfigurationManager {
	mock := &MockConfigurationManager{ctrl: ctrl}
	mock.recorder = &MockConfigurationManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationManager) EXPECT() *MockConfigurationManagerMockRecorder {
	return m.recorder
}

// LoadConfiguration mocks base method.
func (m *MockConfigurationManager) LoadConfiguration(ctx context.Context) (*bulkclone.BulkCloneConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfiguration", ctx)
	ret0, _ := ret[0].(*bulkclone.BulkCloneConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfiguration indicates an expected call of LoadConfiguration.
func (mr *MockConfigurationManagerMockRecorder) LoadConfiguration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfiguration", reflect.TypeOf((*MockConfigurationManager)(nil).LoadConfiguration), ctx)
}

// ValidateConfiguration mocks base method.
func (m *MockConfigurationManager) ValidateConfiguration(ctx context.Context, config *bulkclone.BulkCloneConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfiguration", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfiguration indicates an expected call of ValidateConfiguration.
func (mr *MockConfigurationManagerMockRecorder) ValidateConfiguration(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfiguration", reflect.TypeOf((*MockConfigurationManager)(nil).ValidateConfiguration), ctx, config)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}
