// Code generated by MockGen. DO NOT EDIT.
// Source: internal/analysis/quality_analyzer.go
//
// Generated by this command:
//
//	mockgen -source=internal/analysis/quality_analyzer.go -destination=internal/analysis/mocks/quality_analyzer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	analysis "github.com/gizzahub/gzh-cli/internal/analysis"
	gomock "go.uber.org/mock/gomock"
)

// MockQualityAnalyzer is a mock of QualityAnalyzer interface.
type MockQualityAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockQualityAnalyzerMockRecorder
	isgomock struct{}
}

// MockQualityAnalyzerMockRecorder is the mock recorder for MockQualityAnalyzer.
type MockQualityAnalyzerMockRecorder struct {
	mock *MockQualityAnalyzer
}

// NewMockQualityAnalyzer creates a new mock instance.
func NewMockQualityAnalyzer(ctrl *gomock.Controller) *MockQualityAnalyzer {
	mock := &MockQualityAnalyzer{ctrl: ctrl}
	mock.recorder = &MockQualityAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQualityAnalyzer) EXPECT() *MockQualityAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockQualityAnalyzer) Analyze(ctx context.Context, path string) (*analysis.QualityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, path)
	ret0, _ := ret[0].(*analysis.QualityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockQualityAnalyzerMockRecorder) Analyze(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockQualityAnalyzer)(nil).Analyze), ctx, path)
}

// IsAvailable mocks base method.
func (m *MockQualityAnalyzer) IsAvailable(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockQualityAnalyzerMockRecorder) IsAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockQualityAnalyzer)(nil).IsAvailable), ctx)
}

// Language mocks base method.
func (m *MockQualityAnalyzer) Language() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockQualityAnalyzerMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockQualityAnalyzer)(nil).Language))
}

// Name mocks base method.
func (m *MockQualityAnalyzer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockQualityAnalyzerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockQualityAnalyzer)(nil).Name))
}
