// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/config/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=pkg/config/interfaces.go -destination=pkg/config/mocks/config_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	config "github.com/gizzahub/gzh-cli/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// GetSearchPaths mocks base method.
func (m *MockLoader) GetSearchPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSearchPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSearchPaths indicates an expected call of GetSearchPaths.
func (mr *MockLoaderMockRecorder) GetSearchPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSearchPaths", reflect.TypeOf((*MockLoader)(nil).GetSearchPaths))
}

// LoadConfig mocks base method.
func (m *MockLoader) LoadConfig(ctx context.Context) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfig", ctx)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfig indicates an expected call of LoadConfig.
func (mr *MockLoaderMockRecorder) LoadConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfig", reflect.TypeOf((*MockLoader)(nil).LoadConfig), ctx)
}

// LoadConfigFromFile mocks base method.
func (m *MockLoader) LoadConfigFromFile(ctx context.Context, filename string) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigFromFile", ctx, filename)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfigFromFile indicates an expected call of LoadConfigFromFile.
func (mr *MockLoaderMockRecorder) LoadConfigFromFile(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigFromFile", reflect.TypeOf((*MockLoader)(nil).LoadConfigFromFile), ctx, filename)
}

// LoadConfigFromReader mocks base method.
func (m *MockLoader) LoadConfigFromReader(ctx context.Context, reader io.Reader) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigFromReader", ctx, reader)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfigFromReader indicates an expected call of LoadConfigFromReader.
func (mr *MockLoaderMockRecorder) LoadConfigFromReader(ctx, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigFromReader", reflect.TypeOf((*MockLoader)(nil).LoadConfigFromReader), ctx, reader)
}

// SetSearchPaths mocks base method.
func (m *MockLoader) SetSearchPaths(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSearchPaths", paths)
}

// SetSearchPaths indicates an expected call of SetSearchPaths.
func (mr *MockLoaderMockRecorder) SetSearchPaths(paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSearchPaths", reflect.TypeOf((*MockLoader)(nil).SetSearchPaths), paths)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// GetValidationErrors mocks base method.
func (m *MockValidator) GetValidationErrors(ctx context.Context, arg1 *config.Config) []config.ValidationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidationErrors", ctx, arg1)
	ret0, _ := ret[0].([]config.ValidationError)
	return ret0
}

// GetValidationErrors indicates an expected call of GetValidationErrors.
func (mr *MockValidatorMockRecorder) GetValidationErrors(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidationErrors", reflect.TypeOf((*MockValidator)(nil).GetValidationErrors), ctx, arg1)
}

// IsValid mocks base method.
func (m *MockValidator) IsValid(ctx context.Context, arg1 *config.Config) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", ctx, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockValidatorMockRecorder) IsValid(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockValidator)(nil).IsValid), ctx, arg1)
}

// ValidateConfig mocks base method.
func (m *MockValidator) ValidateConfig(ctx context.Context, arg1 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfig", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfig indicates an expected call of ValidateConfig.
func (mr *MockValidatorMockRecorder) ValidateConfig(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfig", reflect.TypeOf((*MockValidator)(nil).ValidateConfig), ctx, arg1)
}

// ValidateConfigFile mocks base method.
func (m *MockValidator) ValidateConfigFile(ctx context.Context, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfigFile", ctx, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfigFile indicates an expected call of ValidateConfigFile.
func (mr *MockValidatorMockRecorder) ValidateConfigFile(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfigFile", reflect.TypeOf((*MockValidator)(nil).ValidateConfigFile), ctx, filename)
}

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// GetSupportedFormats mocks base method.
func (m *MockParser) GetSupportedFormats() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedFormats")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedFormats indicates an expected call of GetSupportedFormats.
func (mr *MockParserMockRecorder) GetSupportedFormats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedFormats", reflect.TypeOf((*MockParser)(nil).GetSupportedFormats))
}

// IsFormatSupported mocks base method.
func (m *MockParser) IsFormatSupported(format string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFormatSupported", format)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFormatSupported indicates an expected call of IsFormatSupported.
func (mr *MockParserMockRecorder) IsFormatSupported(format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFormatSupported", reflect.TypeOf((*MockParser)(nil).IsFormatSupported), format)
}

// ParseConfig mocks base method.
func (m *MockParser) ParseConfig(ctx context.Context, data []byte) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConfig", ctx, data)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConfig indicates an expected call of ParseConfig.
func (mr *MockParserMockRecorder) ParseConfig(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfig", reflect.TypeOf((*MockParser)(nil).ParseConfig), ctx, data)
}

// ParseConfigWithFormat mocks base method.
func (m *MockParser) ParseConfigWithFormat(ctx context.Context, data []byte, format string) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConfigWithFormat", ctx, data, format)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConfigWithFormat indicates an expected call of ParseConfigWithFormat.
func (mr *MockParserMockRecorder) ParseConfigWithFormat(ctx, data, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfigWithFormat", reflect.TypeOf((*MockParser)(nil).ParseConfigWithFormat), ctx, data, format)
}

// MockSchemaValidator is a mock of SchemaValidator interface.
type MockSchemaValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaValidatorMockRecorder
	isgomock struct{}
}

// MockSchemaValidatorMockRecorder is the mock recorder for MockSchemaValidator.
type MockSchemaValidatorMockRecorder struct {
	mock *MockSchemaValidator
}

// NewMockSchemaValidator creates a new mock instance.
func NewMockSchemaValidator(ctrl *gomock.Controller) *MockSchemaValidator {
	mock := &MockSchemaValidator{ctrl: ctrl}
	mock.recorder = &MockSchemaValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaValidator) EXPECT() *MockSchemaValidatorMockRecorder {
	return m.recorder
}

// GetConfigSchema mocks base method.
func (m *MockSchemaValidator) GetConfigSchema() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigSchema")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigSchema indicates an expected call of GetConfigSchema.
func (mr *MockSchemaValidatorMockRecorder) GetConfigSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigSchema", reflect.TypeOf((*MockSchemaValidator)(nil).GetConfigSchema))
}

// ValidateSchema mocks base method.
func (m *MockSchemaValidator) ValidateSchema(ctx context.Context, data []byte, schemaPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSchema", ctx, data, schemaPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSchema indicates an expected call of ValidateSchema.
func (mr *MockSchemaValidatorMockRecorder) ValidateSchema(ctx, data, schemaPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSchema", reflect.TypeOf((*MockSchemaValidator)(nil).ValidateSchema), ctx, data, schemaPath)
}

// ValidateStructure mocks base method.
func (m *MockSchemaValidator) ValidateStructure(ctx context.Context, arg1 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStructure", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStructure indicates an expected call of ValidateStructure.
func (mr *MockSchemaValidatorMockRecorder) ValidateStructure(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStructure", reflect.TypeOf((*MockSchemaValidator)(nil).ValidateStructure), ctx, arg1)
}

// MockProviderManager is a mock of ProviderManager interface.
type MockProviderManager struct {
	ctrl     *gomock.Controller
	recorder *MockProviderManagerMockRecorder
	isgomock struct{}
}

// MockProviderManagerMockRecorder is the mock recorder for MockProviderManager.
type MockProviderManagerMockRecorder struct {
	mock *MockProviderManager
}

// NewMockProviderManager creates a new mock instance.
func NewMockProviderManager(ctrl *gomock.Controller) *MockProviderManager {
	mock := &MockProviderManager{ctrl: ctrl}
	mock.recorder = &MockProviderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderManager) EXPECT() *MockProviderManagerMockRecorder {
	return m.recorder
}

// GetProvider mocks base method.
func (m *MockProviderManager) GetProvider(ctx context.Context, name string) (*config.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", ctx, name)
	ret0, _ := ret[0].(*config.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockProviderManagerMockRecorder) GetProvider(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockProviderManager)(nil).GetProvider), ctx, name)
}

// GetProviders mocks base method.
func (m *MockProviderManager) GetProviders(ctx context.Context) (map[string]config.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", ctx)
	ret0, _ := ret[0].(map[string]config.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockProviderManagerMockRecorder) GetProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockProviderManager)(nil).GetProviders), ctx)
}

// GetSupportedProviders mocks base method.
func (m *MockProviderManager) GetSupportedProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedProviders indicates an expected call of GetSupportedProviders.
func (mr *MockProviderManagerMockRecorder) GetSupportedProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedProviders", reflect.TypeOf((*MockProviderManager)(nil).GetSupportedProviders))
}

// ValidateProvider mocks base method.
func (m *MockProviderManager) ValidateProvider(ctx context.Context, provider *config.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateProvider", ctx, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateProvider indicates an expected call of ValidateProvider.
func (mr *MockProviderManagerMockRecorder) ValidateProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateProvider", reflect.TypeOf((*MockProviderManager)(nil).ValidateProvider), ctx, provider)
}

// MockDirectoryResolverInterface is a mock of DirectoryResolverInterface interface.
type MockDirectoryResolverInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryResolverInterfaceMockRecorder
	isgomock struct{}
}

// MockDirectoryResolverInterfaceMockRecorder is the mock recorder for MockDirectoryResolverInterface.
type MockDirectoryResolverInterfaceMockRecorder struct {
	mock *MockDirectoryResolverInterface
}

// NewMockDirectoryResolverInterface creates a new mock instance.
func NewMockDirectoryResolverInterface(ctrl *gomock.Controller) *MockDirectoryResolverInterface {
	mock := &MockDirectoryResolverInterface{ctrl: ctrl}
	mock.recorder = &MockDirectoryResolverInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryResolverInterface) EXPECT() *MockDirectoryResolverInterfaceMockRecorder {
	return m.recorder
}

// ExpandPath mocks base method.
func (m *MockDirectoryResolverInterface) ExpandPath(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandPath", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExpandPath indicates an expected call of ExpandPath.
func (mr *MockDirectoryResolverInterfaceMockRecorder) ExpandPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandPath", reflect.TypeOf((*MockDirectoryResolverInterface)(nil).ExpandPath), path)
}

// ResolveDirectories mocks base method.
func (m *MockDirectoryResolverInterface) ResolveDirectories(ctx context.Context, arg1 *config.Config) ([]config.RepositoryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDirectories", ctx, arg1)
	ret0, _ := ret[0].([]config.RepositoryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDirectories indicates an expected call of ResolveDirectories.
func (mr *MockDirectoryResolverInterfaceMockRecorder) ResolveDirectories(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDirectories", reflect.TypeOf((*MockDirectoryResolverInterface)(nil).ResolveDirectories), ctx, arg1)
}

// ResolveDirectory mocks base method.
func (m *MockDirectoryResolverInterface) ResolveDirectory(ctx context.Context, pattern string, metadata map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDirectory", ctx, pattern, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDirectory indicates an expected call of ResolveDirectory.
func (mr *MockDirectoryResolverInterfaceMockRecorder) ResolveDirectory(ctx, pattern, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDirectory", reflect.TypeOf((*MockDirectoryResolverInterface)(nil).ResolveDirectory), ctx, pattern, metadata)
}

// ValidatePath mocks base method.
func (m *MockDirectoryResolverInterface) ValidatePath(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePath", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePath indicates an expected call of ValidatePath.
func (mr *MockDirectoryResolverInterfaceMockRecorder) ValidatePath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePath", reflect.TypeOf((*MockDirectoryResolverInterface)(nil).ValidatePath), ctx, path)
}

// MockFilterService is a mock of FilterService interface.
type MockFilterService struct {
	ctrl     *gomock.Controller
	recorder *MockFilterServiceMockRecorder
	isgomock struct{}
}

// MockFilterServiceMockRecorder is the mock recorder for MockFilterService.
type MockFilterServiceMockRecorder struct {
	mock *MockFilterService
}

// NewMockFilterService creates a new mock instance.
func NewMockFilterService(ctrl *gomock.Controller) *MockFilterService {
	mock := &MockFilterService{ctrl: ctrl}
	mock.recorder = &MockFilterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterService) EXPECT() *MockFilterServiceMockRecorder {
	return m.recorder
}

// ApplyFilters mocks base method.
func (m *MockFilterService) ApplyFilters(ctx context.Context, repositories []config.Repository, filters *config.RepositoryFilter) ([]config.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyFilters", ctx, repositories, filters)
	ret0, _ := ret[0].([]config.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyFilters indicates an expected call of ApplyFilters.
func (mr *MockFilterServiceMockRecorder) ApplyFilters(ctx, repositories, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyFilters", reflect.TypeOf((*MockFilterService)(nil).ApplyFilters), ctx, repositories, filters)
}

// GetFilterStats mocks base method.
func (m *MockFilterService) GetFilterStats(ctx context.Context, repositories []config.Repository, filter *config.RepositoryFilter) (*config.FilterStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterStats", ctx, repositories, filter)
	ret0, _ := ret[0].(*config.FilterStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilterStats indicates an expected call of GetFilterStats.
func (mr *MockFilterServiceMockRecorder) GetFilterStats(ctx, repositories, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterStats", reflect.TypeOf((*MockFilterService)(nil).GetFilterStats), ctx, repositories, filter)
}

// MatchesFilter mocks base method.
func (m *MockFilterService) MatchesFilter(ctx context.Context, repository config.Repository, filter *config.RepositoryFilter) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesFilter", ctx, repository, filter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchesFilter indicates an expected call of MatchesFilter.
func (mr *MockFilterServiceMockRecorder) MatchesFilter(ctx, repository, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesFilter", reflect.TypeOf((*MockFilterService)(nil).MatchesFilter), ctx, repository, filter)
}

// ValidateFilter mocks base method.
func (m *MockFilterService) ValidateFilter(ctx context.Context, filter *config.RepositoryFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFilter", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFilter indicates an expected call of ValidateFilter.
func (mr *MockFilterServiceMockRecorder) ValidateFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFilter", reflect.TypeOf((*MockFilterService)(nil).ValidateFilter), ctx, filter)
}

// MockIntegrationService is a mock of IntegrationService interface.
type MockIntegrationService struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationServiceMockRecorder
	isgomock struct{}
}

// MockIntegrationServiceMockRecorder is the mock recorder for MockIntegrationService.
type MockIntegrationServiceMockRecorder struct {
	mock *MockIntegrationService
}

// NewMockIntegrationService creates a new mock instance.
func NewMockIntegrationService(ctrl *gomock.Controller) *MockIntegrationService {
	mock := &MockIntegrationService{ctrl: ctrl}
	mock.recorder = &MockIntegrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationService) EXPECT() *MockIntegrationServiceMockRecorder {
	return m.recorder
}

// ExecuteBulkClone mocks base method.
func (m *MockIntegrationService) ExecuteBulkClone(ctx context.Context, targets []config.BulkCloneTarget) (*config.BulkCloneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkClone", ctx, targets)
	ret0, _ := ret[0].(*config.BulkCloneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkClone indicates an expected call of ExecuteBulkClone.
func (mr *MockIntegrationServiceMockRecorder) ExecuteBulkClone(ctx, targets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkClone", reflect.TypeOf((*MockIntegrationService)(nil).ExecuteBulkClone), ctx, targets)
}

// GetAllTargets mocks base method.
func (m *MockIntegrationService) GetAllTargets(ctx context.Context) ([]config.BulkCloneTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTargets", ctx)
	ret0, _ := ret[0].([]config.BulkCloneTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTargets indicates an expected call of GetAllTargets.
func (mr *MockIntegrationServiceMockRecorder) GetAllTargets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTargets", reflect.TypeOf((*MockIntegrationService)(nil).GetAllTargets), ctx)
}

// GetTargetsByProvider mocks base method.
func (m *MockIntegrationService) GetTargetsByProvider(ctx context.Context, provider string) ([]config.BulkCloneTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetsByProvider", ctx, provider)
	ret0, _ := ret[0].([]config.BulkCloneTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetsByProvider indicates an expected call of GetTargetsByProvider.
func (mr *MockIntegrationServiceMockRecorder) GetTargetsByProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetsByProvider", reflect.TypeOf((*MockIntegrationService)(nil).GetTargetsByProvider), ctx, provider)
}

// ShouldProcessTarget mocks base method.
func (m *MockIntegrationService) ShouldProcessTarget(ctx context.Context, target config.BulkCloneTarget, filters map[string]any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessTarget", ctx, target, filters)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessTarget indicates an expected call of ShouldProcessTarget.
func (mr *MockIntegrationServiceMockRecorder) ShouldProcessTarget(ctx, target, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessTarget", reflect.TypeOf((*MockIntegrationService)(nil).ShouldProcessTarget), ctx, target, filters)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApplyFilters mocks base method.
func (m *MockService) ApplyFilters(ctx context.Context, repositories []config.Repository, filters *config.RepositoryFilter) ([]config.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyFilters", ctx, repositories, filters)
	ret0, _ := ret[0].([]config.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyFilters indicates an expected call of ApplyFilters.
func (mr *MockServiceMockRecorder) ApplyFilters(ctx, repositories, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyFilters", reflect.TypeOf((*MockService)(nil).ApplyFilters), ctx, repositories, filters)
}

// ExecuteBulkClone mocks base method.
func (m *MockService) ExecuteBulkClone(ctx context.Context, targets []config.BulkCloneTarget) (*config.BulkCloneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBulkClone", ctx, targets)
	ret0, _ := ret[0].(*config.BulkCloneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteBulkClone indicates an expected call of ExecuteBulkClone.
func (mr *MockServiceMockRecorder) ExecuteBulkClone(ctx, targets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBulkClone", reflect.TypeOf((*MockService)(nil).ExecuteBulkClone), ctx, targets)
}

// ExpandPath mocks base method.
func (m *MockService) ExpandPath(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandPath", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExpandPath indicates an expected call of ExpandPath.
func (mr *MockServiceMockRecorder) ExpandPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandPath", reflect.TypeOf((*MockService)(nil).ExpandPath), path)
}

// GetAllTargets mocks base method.
func (m *MockService) GetAllTargets(ctx context.Context) ([]config.BulkCloneTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTargets", ctx)
	ret0, _ := ret[0].([]config.BulkCloneTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTargets indicates an expected call of GetAllTargets.
func (mr *MockServiceMockRecorder) GetAllTargets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTargets", reflect.TypeOf((*MockService)(nil).GetAllTargets), ctx)
}

// GetConfigSchema mocks base method.
func (m *MockService) GetConfigSchema() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigSchema")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigSchema indicates an expected call of GetConfigSchema.
func (mr *MockServiceMockRecorder) GetConfigSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigSchema", reflect.TypeOf((*MockService)(nil).GetConfigSchema))
}

// GetFilterStats mocks base method.
func (m *MockService) GetFilterStats(ctx context.Context, repositories []config.Repository, filter *config.RepositoryFilter) (*config.FilterStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterStats", ctx, repositories, filter)
	ret0, _ := ret[0].(*config.FilterStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilterStats indicates an expected call of GetFilterStats.
func (mr *MockServiceMockRecorder) GetFilterStats(ctx, repositories, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterStats", reflect.TypeOf((*MockService)(nil).GetFilterStats), ctx, repositories, filter)
}

// GetProvider mocks base method.
func (m *MockService) GetProvider(ctx context.Context, name string) (*config.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", ctx, name)
	ret0, _ := ret[0].(*config.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockServiceMockRecorder) GetProvider(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockService)(nil).GetProvider), ctx, name)
}

// GetProviders mocks base method.
func (m *MockService) GetProviders(ctx context.Context) (map[string]config.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", ctx)
	ret0, _ := ret[0].(map[string]config.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockServiceMockRecorder) GetProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockService)(nil).GetProviders), ctx)
}

// GetSearchPaths mocks base method.
func (m *MockService) GetSearchPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSearchPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSearchPaths indicates an expected call of GetSearchPaths.
func (mr *MockServiceMockRecorder) GetSearchPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSearchPaths", reflect.TypeOf((*MockService)(nil).GetSearchPaths))
}

// GetSupportedFormats mocks base method.
func (m *MockService) GetSupportedFormats() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedFormats")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedFormats indicates an expected call of GetSupportedFormats.
func (mr *MockServiceMockRecorder) GetSupportedFormats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedFormats", reflect.TypeOf((*MockService)(nil).GetSupportedFormats))
}

// GetSupportedProviders mocks base method.
func (m *MockService) GetSupportedProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedProviders indicates an expected call of GetSupportedProviders.
func (mr *MockServiceMockRecorder) GetSupportedProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedProviders", reflect.TypeOf((*MockService)(nil).GetSupportedProviders))
}

// GetTargetsByProvider mocks base method.
func (m *MockService) GetTargetsByProvider(ctx context.Context, provider string) ([]config.BulkCloneTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetsByProvider", ctx, provider)
	ret0, _ := ret[0].([]config.BulkCloneTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetsByProvider indicates an expected call of GetTargetsByProvider.
func (mr *MockServiceMockRecorder) GetTargetsByProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetsByProvider", reflect.TypeOf((*MockService)(nil).GetTargetsByProvider), ctx, provider)
}

// GetValidationErrors mocks base method.
func (m *MockService) GetValidationErrors(ctx context.Context, arg1 *config.Config) []config.ValidationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidationErrors", ctx, arg1)
	ret0, _ := ret[0].([]config.ValidationError)
	return ret0
}

// GetValidationErrors indicates an expected call of GetValidationErrors.
func (mr *MockServiceMockRecorder) GetValidationErrors(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidationErrors", reflect.TypeOf((*MockService)(nil).GetValidationErrors), ctx, arg1)
}

// IsFormatSupported mocks base method.
func (m *MockService) IsFormatSupported(format string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFormatSupported", format)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFormatSupported indicates an expected call of IsFormatSupported.
func (mr *MockServiceMockRecorder) IsFormatSupported(format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFormatSupported", reflect.TypeOf((*MockService)(nil).IsFormatSupported), format)
}

// IsValid mocks base method.
func (m *MockService) IsValid(ctx context.Context, arg1 *config.Config) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", ctx, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockServiceMockRecorder) IsValid(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockService)(nil).IsValid), ctx, arg1)
}

// LoadConfig mocks base method.
func (m *MockService) LoadConfig(ctx context.Context) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfig", ctx)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfig indicates an expected call of LoadConfig.
func (mr *MockServiceMockRecorder) LoadConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfig", reflect.TypeOf((*MockService)(nil).LoadConfig), ctx)
}

// LoadConfigFromFile mocks base method.
func (m *MockService) LoadConfigFromFile(ctx context.Context, filename string) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigFromFile", ctx, filename)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfigFromFile indicates an expected call of LoadConfigFromFile.
func (mr *MockServiceMockRecorder) LoadConfigFromFile(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigFromFile", reflect.TypeOf((*MockService)(nil).LoadConfigFromFile), ctx, filename)
}

// LoadConfigFromReader mocks base method.
func (m *MockService) LoadConfigFromReader(ctx context.Context, reader io.Reader) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigFromReader", ctx, reader)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadConfigFromReader indicates an expected call of LoadConfigFromReader.
func (mr *MockServiceMockRecorder) LoadConfigFromReader(ctx, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigFromReader", reflect.TypeOf((*MockService)(nil).LoadConfigFromReader), ctx, reader)
}

// MatchesFilter mocks base method.
func (m *MockService) MatchesFilter(ctx context.Context, repository config.Repository, filter *config.RepositoryFilter) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesFilter", ctx, repository, filter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchesFilter indicates an expected call of MatchesFilter.
func (mr *MockServiceMockRecorder) MatchesFilter(ctx, repository, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesFilter", reflect.TypeOf((*MockService)(nil).MatchesFilter), ctx, repository, filter)
}

// ParseConfig mocks base method.
func (m *MockService) ParseConfig(ctx context.Context, data []byte) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConfig", ctx, data)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConfig indicates an expected call of ParseConfig.
func (mr *MockServiceMockRecorder) ParseConfig(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfig", reflect.TypeOf((*MockService)(nil).ParseConfig), ctx, data)
}

// ParseConfigWithFormat mocks base method.
func (m *MockService) ParseConfigWithFormat(ctx context.Context, data []byte, format string) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConfigWithFormat", ctx, data, format)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConfigWithFormat indicates an expected call of ParseConfigWithFormat.
func (mr *MockServiceMockRecorder) ParseConfigWithFormat(ctx, data, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfigWithFormat", reflect.TypeOf((*MockService)(nil).ParseConfigWithFormat), ctx, data, format)
}

// ResolveDirectories mocks base method.
func (m *MockService) ResolveDirectories(ctx context.Context, arg1 *config.Config) ([]config.RepositoryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDirectories", ctx, arg1)
	ret0, _ := ret[0].([]config.RepositoryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDirectories indicates an expected call of ResolveDirectories.
func (mr *MockServiceMockRecorder) ResolveDirectories(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDirectories", reflect.TypeOf((*MockService)(nil).ResolveDirectories), ctx, arg1)
}

// ResolveDirectory mocks base method.
func (m *MockService) ResolveDirectory(ctx context.Context, pattern string, metadata map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDirectory", ctx, pattern, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDirectory indicates an expected call of ResolveDirectory.
func (mr *MockServiceMockRecorder) ResolveDirectory(ctx, pattern, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDirectory", reflect.TypeOf((*MockService)(nil).ResolveDirectory), ctx, pattern, metadata)
}

// SetSearchPaths mocks base method.
func (m *MockService) SetSearchPaths(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSearchPaths", paths)
}

// SetSearchPaths indicates an expected call of SetSearchPaths.
func (mr *MockServiceMockRecorder) SetSearchPaths(paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSearchPaths", reflect.TypeOf((*MockService)(nil).SetSearchPaths), paths)
}

// ShouldProcessTarget mocks base method.
func (m *MockService) ShouldProcessTarget(ctx context.Context, target config.BulkCloneTarget, filters map[string]any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessTarget", ctx, target, filters)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessTarget indicates an expected call of ShouldProcessTarget.
func (mr *MockServiceMockRecorder) ShouldProcessTarget(ctx, target, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessTarget", reflect.TypeOf((*MockService)(nil).ShouldProcessTarget), ctx, target, filters)
}

// ValidateConfig mocks base method.
func (m *MockService) ValidateConfig(ctx context.Context, arg1 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfig", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfig indicates an expected call of ValidateConfig.
func (mr *MockServiceMockRecorder) ValidateConfig(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfig", reflect.TypeOf((*MockService)(nil).ValidateConfig), ctx, arg1)
}

// ValidateConfigFile mocks base method.
func (m *MockService) ValidateConfigFile(ctx context.Context, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfigFile", ctx, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfigFile indicates an expected call of ValidateConfigFile.
func (mr *MockServiceMockRecorder) ValidateConfigFile(ctx, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfigFile", reflect.TypeOf((*MockService)(nil).ValidateConfigFile), ctx, filename)
}

// ValidateFilter mocks base method.
func (m *MockService) ValidateFilter(ctx context.Context, filter *config.RepositoryFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFilter", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFilter indicates an expected call of ValidateFilter.
func (mr *MockServiceMockRecorder) ValidateFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFilter", reflect.TypeOf((*MockService)(nil).ValidateFilter), ctx, filter)
}

// ValidatePath mocks base method.
func (m *MockService) ValidatePath(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePath", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePath indicates an expected call of ValidatePath.
func (mr *MockServiceMockRecorder) ValidatePath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePath", reflect.TypeOf((*MockService)(nil).ValidatePath), ctx, path)
}

// ValidateProvider mocks base method.
func (m *MockService) ValidateProvider(ctx context.Context, provider *config.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateProvider", ctx, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateProvider indicates an expected call of ValidateProvider.
func (mr *MockServiceMockRecorder) ValidateProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateProvider", reflect.TypeOf((*MockService)(nil).ValidateProvider), ctx, provider)
}

// ValidateSchema mocks base method.
func (m *MockService) ValidateSchema(ctx context.Context, data []byte, schemaPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSchema", ctx, data, schemaPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSchema indicates an expected call of ValidateSchema.
func (mr *MockServiceMockRecorder) ValidateSchema(ctx, data, schemaPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSchema", reflect.TypeOf((*MockService)(nil).ValidateSchema), ctx, data, schemaPath)
}

// ValidateStructure mocks base method.
func (m *MockService) ValidateStructure(ctx context.Context, arg1 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStructure", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStructure indicates an expected call of ValidateStructure.
func (mr *MockServiceMockRecorder) ValidateStructure(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStructure", reflect.TypeOf((*MockService)(nil).ValidateStructure), ctx, arg1)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Changes mocks base method.
func (m *MockWatcher) Changes() <-chan config.ChangeEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changes")
	ret0, _ := ret[0].(<-chan config.ChangeEvent)
	return ret0
}

// Changes indicates an expected call of Changes.
func (mr *MockWatcherMockRecorder) Changes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changes", reflect.TypeOf((*MockWatcher)(nil).Changes))
}

// OnChange mocks base method.
func (m *MockWatcher) OnChange(callback func(config.ChangeEvent)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnChange", callback)
}

// OnChange indicates an expected call of OnChange.
func (mr *MockWatcherMockRecorder) OnChange(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockWatcher)(nil).OnChange), callback)
}

// StartWatching mocks base method.
func (m *MockWatcher) StartWatching(ctx context.Context, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartWatching", ctx, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartWatching indicates an expected call of StartWatching.
func (mr *MockWatcherMockRecorder) StartWatching(ctx, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWatching", reflect.TypeOf((*MockWatcher)(nil).StartWatching), ctx, paths)
}

// StopWatching mocks base method.
func (m *MockWatcher) StopWatching() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWatching")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWatching indicates an expected call of StopWatching.
func (mr *MockWatcherMockRecorder) StopWatching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWatching", reflect.TypeOf((*MockWatcher)(nil).StopWatching))
}
