name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...

      - name: Auto-merge Dependabot PRs
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;

            // Only auto-merge minor and patch updates
            const title = pr.title;
            const isMinorOrPatch = /bump.*from.*to.*\d+\.\d+\.\d+/.test(title) &&
                                   !title.includes('major');

            if (isMinorOrPatch) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: 'APPROVE'
              });

              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            }
