# Test Coverage Workflow
name: Test Coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run unit tests with coverage
      run: |
        go test -race -coverprofile=coverage.out -covermode=atomic ./cmd/git/...
        go tool cover -html=coverage.out -o coverage.html
        
    - name: Run integration tests with coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        GITHUB_TEST_ORG: ${{ vars.GITHUB_TEST_ORG || 'gizzahub' }}
        GITLAB_TEST_GROUP: ${{ vars.GITLAB_TEST_GROUP || 'gizzahub' }}
        GITEA_TEST_ORG: ${{ vars.GITEA_TEST_ORG || 'gizzahub' }}
      run: |
        go test -tags=integration -race -coverprofile=integration_coverage.out -covermode=atomic ./cmd/git/...
      continue-on-error: true
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out,./integration_coverage.out
        fail_ci_if_error: false
        verbose: true
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.out
          coverage.html
          integration_coverage.out